---
title: "TidyTuesday"
author: "Solal Chauquet"
date: "5/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## TidyTuesday

```{r}
library(tidyverse)
library(ggplot2)
sessionInfo()
```

28/05/19: 
Wine ranking

```{r 28/05}
library(ggstance)
#wine <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-28/winemag-data-130k-v2.csv")

color = RColorBrewer::brewer.pal(3,'Blues')
lineplot = wine %>%
  group_by(country) %>%
  drop_na(country) %>%
  summarise(mean = mean(points), 
            SD = sd(points), 
            n = n()) %>%
  drop_na(SD) %>%
  arrange(mean) %>%
  mutate(signif = as.factor(ifelse(n>100,color[1],color[3])))

x= lineplot$country
lineplot$country = factor(lineplot$country, levels = x)
  
p = ggplot(lineplot, aes(y=country, x=mean, xmin=mean-SD, xmax=mean+SD, color= I(signif))) +
  geom_point() +
  geom_errorbarh() +
  ylab('') +
  xlab('Mean Review Score') +
  theme_light() +
  scale_color_discrete('Number of review:', labels= c('< 100 review', '> 100 review')) +
  labs(title = "Which country produce the best wine?",
       caption = "Source: WineEnthusiast") +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.y  = element_text(size=8.5),
        panel.grid.major.x=element_blank(),
        panel.grid.minor.x=element_blank()) 
p
ggsave(p, filename = 'WineRanking.jpeg', device = 'jpeg', path = '/Users/s.chauquet/Documents/DataScience/TidyTuesday')
```

